[project]
name = "illustradle"
version = "0.1.0"
description = "Hackathon project"
readme = "README.md"
requires-python = ">=3.12.9"
dependencies = [
    "flask==3.1.0",
    "openai>=1.69.0",
    "python-dotenv>=1.1.0",
]
